#!/bin/sh

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

RED="\e[31m"
GREEN="\e[32m"
ENDCOLOR="\e[0m"

case "$1" in
    configure)
        # Activate package triggers
        dpkg-trigger update-workbench

# Initialize and migrate configuration database.
        echo "${GREEN}Updating configuration database ...${ENDCOLOR}"
        omv-confdbadm create "conf.system.network.dnshost"
        if [ -n "$2" ]; then
            omv-confdbadm migrate "conf.system.network.dnshost" "${2}"
        fi

    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument" >&2
        exit 1
    ;;
esac

exit 0
